name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  Atelier:
    uses: ./.github/workflows/discover.yaml
    with:
      tool: .#
    permissions:
      contents: read
      checks: write
      id-token: write
